"""Generate a test PDF with safe + phishing links for testing SentinelX."""

from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor
from reportlab.lib.units import cm
from reportlab.pdfgen import canvas

OUTPUT = "test_links.pdf"

# Links to embed in the PDF
LINKS = [
    # (label, url, description)
    ("Google", "https://www.google.com", "SAFE — whitelisted, should load instantly"),
    ("GitHub", "https://github.com", "SAFE — whitelisted, should load instantly"),
    ("Wikipedia", "https://en.wikipedia.org", "SAFE — whitelisted, should load instantly"),
    ("PayPal Fake", "http://paypa1-secure-login.xyz/verify/account", "PHISHING — lookalike domain, should be BLOCKED"),
    ("Google Fake", "http://g00gle-verify.tk/login", "PHISHING — lookalike + .tk TLD, should be BLOCKED"),
    ("Amazon Fake", "http://arnazon-security.ml/update", "PHISHING — lookalike + .ml TLD, should be BLOCKED"),
    ("Suspicious IP", "http://192.168.1.100/admin", "BYPASSES DNS — raw IP, no DNS lookup"),
    ("Microsoft", "https://www.microsoft.com", "SAFE — whitelisted"),
    ("Random Legit", "https://stackoverflow.com/questions", "SAFE — whitelisted"),
    ("Shady Domain", "http://free-prize-winner-2026.xyz/claim-now", "PHISHING — suspicious patterns, should be BLOCKED"),
]


def create_pdf():
    c = canvas.Canvas(OUTPUT, pagesize=A4)
    width, height = A4

    # Title
    c.setFont("Helvetica-Bold", 22)
    c.setFillColor(HexColor("#1a1a2e"))
    c.drawString(2 * cm, height - 3 * cm, "SentinelX — Test Links")

    c.setFont("Helvetica", 11)
    c.setFillColor(HexColor("#555555"))
    c.drawString(2 * cm, height - 3.8 * cm,
                 "Click each link below to test the phishing interceptor.")
    c.drawString(2 * cm, height - 4.4 * cm,
                 "Safe links should load normally. Phishing links should show the block page.")

    # Divider
    c.setStrokeColor(HexColor("#cccccc"))
    c.line(2 * cm, height - 5 * cm, width - 2 * cm, height - 5 * cm)

    y = height - 6 * cm

    for i, (label, url, desc) in enumerate(LINKS, 1):
        # Number + label
        c.setFont("Helvetica-Bold", 13)
        if "PHISHING" in desc:
            c.setFillColor(HexColor("#cc0000"))
        elif "SAFE" in desc:
            c.setFillColor(HexColor("#006600"))
        else:
            c.setFillColor(HexColor("#cc6600"))
        c.drawString(2 * cm, y, f"{i}. {label}")

        # Clickable URL (blue, underlined)
        c.setFont("Courier", 9)
        c.setFillColor(HexColor("#0066cc"))
        url_y = y - 0.5 * cm
        text_width = c.stringWidth(url, "Courier", 9)
        c.drawString(2.5 * cm, url_y, url)
        # Make it clickable
        c.linkURL(url, (2.5 * cm, url_y - 2, 2.5 * cm + text_width, url_y + 10))

        # Description
        c.setFont("Helvetica", 9)
        c.setFillColor(HexColor("#888888"))
        c.drawString(2.5 * cm, url_y - 0.5 * cm, f"→ {desc}")

        y -= 2 * cm

        if y < 3 * cm:
            c.showPage()
            y = height - 3 * cm

    # Footer
    c.setFont("Helvetica", 8)
    c.setFillColor(HexColor("#aaaaaa"))
    c.drawString(2 * cm, 1.5 * cm, "Generated by SentinelX test suite")

    c.save()
    print(f"PDF created: {OUTPUT}")


if __name__ == "__main__":
    create_pdf()
