"""Email alert system — sends SMTP alerts to the security team when leaks are found."""

import smtplib
import ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

from db.models import mark_alerted
from utils.logger import setup_logger
import config

log = setup_logger("alert")


def _build_html_report(findings: list[dict]) -> str:
    """Build an HTML email body from scan findings."""
    critical = [f for f in findings if f["severity"] == "CRITICAL"]
    high = [f for f in findings if f["severity"] == "HIGH"]
    medium = [f for f in findings if f["severity"] == "MEDIUM"]
    low = [f for f in findings if f["severity"] == "LOW"]

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    rows = ""
    for f in findings:
        color = {
            "CRITICAL": "#dc3545",
            "HIGH": "#fd7e14",
            "MEDIUM": "#ffc107",
            "LOW": "#17a2b8",
        }.get(f["severity"], "#6c757d")

        scan_type = f.get("type", "unknown").upper()
        detail = ""
        if f["type"] == "breach":
            detail = f"Email: {f['email']}<br>Breach: {f['breach_name']} ({f['breach_date']})<br>Exposed: {f['data_exposed']}"
        elif f["type"] == "password":
            detail = f"Email: {f['email']}<br>Breaches: {f['breaches']}<br>k-Anon prefix: {f['k_anon_prefix']} ({f['candidates_checked']} candidates)"
        elif f["type"] == "github":
            detail = f"Repo: {f['repo']}<br>File: {f['file_path']}<br>Keyword: {f['keyword']}"
        elif f["type"] == "paste":
            detail = f"URL: {f['paste_url']}<br>Title: {f['title']}"

        rows += f"""
        <tr>
            <td style="padding:8px;border:1px solid #ddd;"><span style="color:{color};font-weight:bold;">{f['severity']}</span></td>
            <td style="padding:8px;border:1px solid #ddd;">{scan_type}</td>
            <td style="padding:8px;border:1px solid #ddd;">{detail}</td>
        </tr>"""

    html = f"""
    <html>
    <body style="font-family:Arial,sans-serif;color:#333;">
        <h2 style="color:#dc3545;">🚨 SentinelX Credential Leak Alert</h2>
        <p><strong>Organization:</strong> {config.ORG_NAME} ({config.ORG_DOMAIN})</p>
        <p><strong>Scan Time:</strong> {timestamp}</p>

        <h3>Summary</h3>
        <ul>
            <li><span style="color:#dc3545;font-weight:bold;">CRITICAL: {len(critical)}</span></li>
            <li><span style="color:#fd7e14;font-weight:bold;">HIGH: {len(high)}</span></li>
            <li><span style="color:#ffc107;font-weight:bold;">MEDIUM: {len(medium)}</span></li>
            <li><span style="color:#17a2b8;">LOW: {len(low)}</span></li>
        </ul>

        <h3>Detailed Findings ({len(findings)} total)</h3>
        <table style="border-collapse:collapse;width:100%;">
            <tr style="background:#f8f9fa;">
                <th style="padding:8px;border:1px solid #ddd;text-align:left;">Severity</th>
                <th style="padding:8px;border:1px solid #ddd;text-align:left;">Type</th>
                <th style="padding:8px;border:1px solid #ddd;text-align:left;">Details</th>
            </tr>
            {rows}
        </table>

        <hr style="margin-top:20px;">
        <p style="font-size:12px;color:#888;">
            This alert was generated by SentinelX Credential Leak Monitor.<br>
            Immediate action recommended for CRITICAL and HIGH severity findings.
        </p>
    </body>
    </html>
    """
    return html


def send_alert(findings: list[dict]) -> bool:
    """Send an email alert with all new findings to the security team.

    Returns True if email was sent successfully.
    """
    if not findings:
        log.info("No new findings — skipping alert")
        return False

    if not config.SMTP_USER or not config.SMTP_PASSWORD:
        log.error("SMTP credentials not configured — cannot send alert")
        return False

    critical_count = sum(1 for f in findings if f["severity"] == "CRITICAL")
    high_count = sum(1 for f in findings if f["severity"] == "HIGH")
    total = len(findings)

    subject = f"[SentinelX] 🚨 {total} credential leak(s) detected"
    if critical_count:
        subject += f" — {critical_count} CRITICAL"
    elif high_count:
        subject += f" — {high_count} HIGH"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = config.ALERT_FROM
    msg["To"] = ", ".join(config.ALERT_TO)

    # Plain text fallback
    plain_text = f"SentinelX Credential Leak Alert\n\n{total} findings detected.\n\n"
    for f in findings:
        plain_text += f"[{f['severity']}] {f['finding']}\n"

    html_body = _build_html_report(findings)

    msg.attach(MIMEText(plain_text, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    try:
        log.info(f"Sending alert email to {config.ALERT_TO}...")
        context = ssl.create_default_context()
        with smtplib.SMTP(config.SMTP_HOST, config.SMTP_PORT) as server:
            server.starttls(context=context)
            server.login(config.SMTP_USER, config.SMTP_PASSWORD)
            server.sendmail(config.ALERT_FROM, config.ALERT_TO, msg.as_string())

        log.info(f"Alert email sent successfully! ({total} findings)")

        # Mark all findings as alerted (dedup for next scan)
        for f in findings:
            mark_alerted(f["scan_result_id"])

        return True

    except Exception as e:
        log.error(f"Failed to send alert email: {type(e).__name__}: {e}")
        return False
